# Generated by Django 5.2.4 on 2025-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ammo_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='ОБОЙМА'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_to_hit',
            field=models.IntegerField(default=0, verbose_name='БОНУС К ПОПАДАНИЮ'),
        ),
        migrations.AddField(
            model_name='item',
            name='damage',
            field=models.CharField(blank=True, max_length=50, verbose_name='УРОН'),
        ),
        migrations.AddField(
            model_name='item',
            name='humanity_loss',
            field=models.PositiveIntegerField(default=0, verbose_name='ПОТЕРЯ ЧЕЛОВЕЧНОСТИ'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('cyberware', 'Киберимплант'), ('weapon', 'Оружие'), ('armor', 'Броня'), ('drug', 'Наркотик'), ('electronics', 'Электроника'), ('info', 'Информация'), ('other', 'Другое')], default='other', max_length=20, verbose_name='ТИП'),
        ),
        migrations.AddField(
            model_name='item',
            name='mount_location',
            field=models.CharField(choices=[('head', 'Голова'), ('eyes', 'Глаза'), ('arms', 'Руки'), ('torso', 'Торс'), ('legs', 'Ноги'), ('nervous', 'Нервная система'), ('internal', 'Внутренний'), ('external', 'Внешний'), ('none', 'Нет')], default='none', max_length=20, verbose_name='МЕСТО УСТАНОВКИ'),
        ),
        migrations.AddField(
            model_name='item',
            name='requirement',
            field=models.CharField(blank=True, max_length=100, verbose_name='ТРЕБОВАНИЕ'),
        ),
        migrations.AddField(
            model_name='item',
            name='sdp',
            field=models.PositiveIntegerField(default=0, verbose_name='СКА'),
        ),
        migrations.AddField(
            model_name='item',
            name='upgrade_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='СЛОТЫ УЛУЧШЕНИЯ'),
        ),
        migrations.AddField(
            model_name='item',
            name='visible_to_vip',
            field=models.BooleanField(default=False, verbose_name='Только для VIP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP статус'),
        ),
    ]
