# Generated by Django 5.2.4 on 2025-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='visible_to_vip',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='item',
            name='required_tier',
            field=models.IntegerField(choices=[(1, 'TIER 1'), (2, 'TIER 2'), (3, 'TIER 3')], default=1, verbose_name='Требуемый TIER'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.IntegerField(choices=[(1, 'TIER 1'), (2, 'TIER 2'), (3, 'TIER 3')], default=1, verbose_name='TIER пользователя'),
        ),
    ]
