# Generated by Django 5.2.4 on 2025-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_item_visible_to_vip_remove_userprofile_is_vip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу'),
            preserve_default=False,
        ),
    ]
